import {Consumable} from './consumable';

export const CONSUMABLES: Consumable[] = [
  { id: 1,    name: 'Apple',        cost: 2, quality: 6, density: 3, imageSrc: 'assets/images/Food/Apple.png' },
  { id: 2,    name: 'Avocado',      cost: 5, quality: 8, density: 3, imageSrc: 'assets/images/Food/Avocado.png' },
  { id: 3,    name: 'Bacon',        cost: 6, quality: 5, density: 2, imageSrc: 'assets/images/Food/Bacon.png' },
  { id: 4,    name: 'Beer',         cost: 3, quality: 3, density: 2, imageSrc: 'assets/images/Food/Beer.png' },
  { id: 5,    name: 'Boar',         cost: 9, quality: 6, density: 7, imageSrc: 'assets/images/Food/Boar.png' },
  { id: 6,    name: 'Bread',        cost: 2, quality: 7, density: 3, imageSrc: 'assets/images/Food/Bread.png' },
  { id: 7,    name: 'Brownie',      cost: 5, quality: 9, density: 3, imageSrc: 'assets/images/Food/Brownie.png' },
  { id: 8,    name: 'Bug',          cost: 1, quality: 1, density: 1, imageSrc: 'assets/images/Food/Bug.png' },
  { id: 9,    name: 'Cheese',       cost: 3, quality: 5, density: 3, imageSrc: 'assets/images/Food/Cheese.png' },
  { id: 10,   name: 'Cherry',       cost: 2, quality: 7, density: 2, imageSrc: 'assets/images/Food/Cherry.png' },
  { id: 11,   name: 'Chicken',      cost: 4, quality: 5, density: 7, imageSrc: 'assets/images/Food/Chicken.png' },
  { id: 12,   name: 'Chicken Leg',  cost: 3, quality: 6, density: 4, imageSrc: 'assets/images/Food/ChickenLeg.png' },
  { id: 13,   name: 'Cookie',       cost: 2, quality: 7, density: 1, imageSrc: 'assets/images/Food/Cookie.png' },
  { id: 14,   name: 'Dragon Fruit', cost: 9, quality: 9, density: 9, imageSrc: 'assets/images/Food/DragonFruit.png' },
  { id: 15,   name: 'Eggplant',     cost: 3, quality: 7, density: 4, imageSrc: 'assets/images/Food/Eggplant.png' },
  { id: 16,   name: 'Eggs',         cost: 2, quality: 6, density: 2, imageSrc: 'assets/images/Food/Eggs.png' },
  { id: 17,   name: 'Fish',         cost: 4, quality: 5, density: 4, imageSrc: 'assets/images/Food/Fish.png' },
  // { id: 20,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/FishFillet.png' },
  // { id: 21,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/FishSteak.png' },
  // { id: 22,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Grub.png' },
  // { id: 23,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Grubs.png' },
  // { id: 24,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Honey.png' },
  // { id: 25,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Honeycomb.png' },
  // { id: 26,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Jam.png' },
  // { id: 27,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Jerky.png' },
  // { id: 28,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Lemon.png' },
  // { id: 29,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Marmalade.png' },
  // { id: 30,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/MelonCantaloupe.png' },
  // { id: 31,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/MelonHoneydew.png' },
  // { id: 32,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/MelonWater.png' },
  // { id: 33,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Moonshine.png' },
  // { id: 34,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Olive.png' },
  // { id: 35,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Onion.png' },
  // { id: 36,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Peach.png' },
  // { id: 37,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/PepperGreen.png' },
  // { id: 38,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Pepperoni.png' },
  // { id: 39,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/PepperRed.png' },
  // { id: 40,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Pickle.png' },
  // { id: 41,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/PickledEggs.png' },
  // { id: 42,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/PieApple.png' },
  // { id: 43,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/PieLemon.png' },
  // { id: 44,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/PiePumpkin.png' },
  // { id: 45,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Pineapple.png' },
  // { id: 46,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Potato.png' },
  // { id: 47,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/PotatoRed.png' },
  // { id: 48,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Pretzel.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Ribs.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Roll.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Saki.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Sardines.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Sashimi.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Sausages.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Shrimp.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Steak.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Stein.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Strawberry.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Sushi.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Tart.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Tomato.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Turnip.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Waffles.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Whiskey.png' },
  // { id: 8,  name: 'Magma', cost: 0, quality: 0, density: 0, imageSrc: 'assets/images/Food/Wine.png' },
];
